version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${DOCKER_ENV:-production}
    container_name: fz-messaging-service-${DOCKER_ENV:-prod}
    ports:
      - "${HOST_PORT:-9093}:${HOST_PORT:-9093}"
    env_file:
      - .env.${DOCKER_ENV:-prod}
    restart: unless-stopped
    # To run a specific environment, set DOCKER_ENV and HOST_PORT:
    # DOCKER_ENV=dev HOST_PORT=9093 docker compose up -d --build
    # DOCKER_ENV=prod HOST_PORT=9095 docker compose up -d --build
